#-*- coding:utf-8 -*-
"""
Django settings for project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import multiprocessing,os,datetime

# 版本号
VERSION = "0.0.1"


# gunicorn worker 进程个数，当WSGI SERVER 是 gunicorn 时有效
GUNICORN_WORKER_NUMBER =  1 # multiprocessing.cpu_count() * 2 + 1
# gunicorn worker 类型， 当WSGI SERVER 是 gunicorn 时有效
GUNICORN_WORKER_CLASS =  "gevent"  # sync gevent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1','*']

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-=0lx=7^sd4=fku($!5_x0g3)m+*=02v*#clzjyddzp^a^g)@='




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'services.datamodel.common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend',
#     'apps.mgr.handlers.teacher.MgrFakeTeacherBackend',
# )

AUTH_USER_MODEL = 'common.User'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LANGUAGE_CODE = 'zh-cn'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'




# session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db' # session save in cached db
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE =7*24 * 60 * 60  # Age of cookie, in seconds (default: 1 week).



RATELIMITTED_CODE = 1001 #API被限速时候的返回码

RATELIMIT_USE_CACHE = 'onedaycache'

# user type 1 means admin, 2 for teacher, 3 for student, 4 for parents
class USER_TYPE:
    ADMIN   = 1
    TEACHER = 2
    STDUENT = 3




Courses = [
    {'id':1, 'name':u'基础班'},
    {'id':2, 'name':u'测试开发班'},
]


CHECK_USER_FOR_CALL = True   #False=无须登录  True 表示需要登录













